E-Tickets/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Models
{
    public class Actor
    {

        [Key]
        public int Id { get; set; }
        [Display(Name = "Profile Picture Url")]
        [Required(ErrorMessage = "Profile Picture is Required")]
        public string ProfilePictureUrl { get; set; }
        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is Required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Full Name must be between 3 and 50 char ")]
        public string FullName { get; set; }
        [Display(Name = "Bio")]
        [Required]
        public string Bio { get; set; }
        //RelationShip
        public List<Actor_Movie> Actors_Movies { get; set; }
    }
}

E-Tickets/Models/Actor_Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Models
{
    public class Actor_Movie
    {
        public int MovieId { get; set; }
        public Movie Movies { get; set; }
        public int ActorId { get; set; }
        public Actor Actors { get; set; }
    }
}

E-Tickets/Models/Cinema.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Models
{
    public class Cinema
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Image Logo")]
        public string Logo { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        //RelationShip
        public List<Movie> Movies { get; set; }
    }
}

E-Tickets/Models/ErrorViewModel.cs
using System;

namespace E_Tickets.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

E-Tickets/Models/Movie.cs
using E_Tickets.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Models
{
    public class Movie
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageUrl { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public MovieCategory MovieCategorey { get; set; }


        //New Table
        public List<Actor_Movie> Actors_Movies { get; set; }
        //RelationShip Cienma
        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinema Cinema { get; set; }

        //RelationShip Producer
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }
    }
}

E-Tickets/Models/Producer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Models
{
    public class Producer
    {
        [Key]
        public int Id { get; set; }
        public string ProfilePictureUrl { get; set; }
        public string FullName { get; set; }
        public string Bio { get; set; }
        //RelationShip
        public List<Movie> Movies { get; set; }
    }
}

E-Tickets/Controllers/ActorsController.cs
using E_Tickets.Data.Services;
using E_Tickets.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Controllers
{
    public class ActorsController : Controller
    {
        public readonly IServicesRepostarycs _services;
        public ActorsController(IServicesRepostarycs services)
        {
            _services = services;
        }
        public async Task<IActionResult> Index()
        {
            var allActor = await _services.GetAllAsync();
            return View(allActor);
        }
        //Get Details
        public async Task<IActionResult> Details(int id)
        {
            var ActorId = await _services.GetIdAsync(id);
            if (ActorId == null) return View("NotFound");
            return View(ActorId);
        }

        //Get //Create Actors
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureUrl,FullName,Bio")]Actor actor)
        {
            if(!ModelState.IsValid)
            {
                return View(actor);
            }
             await _services.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        //Get //Edit Actors
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _services.GetIdAsync(id);
            if (result == null) return View("NotFound");
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("id,FullName,ProfilePictureUrl,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _services.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
        }

    }
}

E-Tickets/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Controllers
{
    public class CinemasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Tickets/Controllers/HomeController.cs
using E_Tickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

E-Tickets/Controllers/MoviesController.cs
using E_Tickets.Data;
using E_Tickets.Data.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Controllers
{
    public class MoviesController : Controller
    {
        public readonly AppDbContext _context;
        public MoviesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var AllMovies = await _context.Movies.Include(n => n.Cinema).OrderBy(x => x.Name).ToListAsync();
            return View(AllMovies);
        }
       
        public IActionResult Details(int id)
        {
            return View();
        }
    }
}

E-Tickets/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Tickets.Controllers
{
    public class ProducersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Tickets/Views/Actors/Create.cshtml
@model Actor


<div class="container mt-5">
    <div class="row m-auto">



        <div class="col-md-8 col-sm-8 col-10">
            <form asp-action="Create">
                <div class="form-group">
                    <div asp-validation-summary="ModelOnly"></div>

                </div>
                <div class="form-group text-center">
                    <img id="profilePicPreview" width="200" />
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePictureUrl">Profile Picture Url</label>
                    <input asp-for="ProfilePictureUrl" id="ProfilePictureUrl" type="text" class="form-control">
                    <span asp-validation-for="ProfilePictureUrl"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FullName">Full Name</label>
                    <input asp-for="FullName" type="text" class="form-control">
                    <span asp-validation-for="FullName"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Bio">Bio</label>
                    <input asp-for="Bio" type="text" class="form-control">
                    <span asp-validation-for="Bio"></span>
                </div>

                <button type="submit" value="Create" class="btn btn-info">Submit</button>
            </form>
        </div>

    </div>
</div>


@section Scripts{

    <script>
        $(document).ready(function () {
            var output = document.getElementById('profilePicPreview');
            output.src = $("#ProfilePictureUrl").val();
        })
        $("#ProfilePictureUrl").on("change", function () {
            var output = document.getElementById('profilePicPreview');
            output.src = $(this).val();
        })
    </script>
}

E-Tickets/Views/Actors/Details.cshtml
@model Actor

<div class="container mt-5">
    <div class="row m-auto">



        <div class="col-md-8 col-sm-8 col-10">
            <form asp-action="Create">
                <div class="form-group">
                    <div asp-validation-summary="ModelOnly"></div>

                </div>
                <div class="form-group text-center">
                    <img id="profilePicPreview" src="@Html.DisplayFor(Item => Item.ProfilePictureUrl)" width="200" />
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePictureUrl">Profile Picture Url</label>
                    <input asp-for="ProfilePictureUrl" id="ProfilePictureUrl" type="text" class="form-control" readonly>
                    <span asp-validation-for="ProfilePictureUrl"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FullName">Full Name</label>
                    <input asp-for="FullName" type="text" class="form-control" readonly>
                    <span asp-validation-for="FullName"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Bio">Bio</label>
                    <input asp-for="Bio" type="text" class="form-control" readonly>
                    <span asp-validation-for="Bio"></span>
                </div>


            </form>
        </div>

    </div>
</div>


@section Scripts{

    <script>
        $(document).ready(function () {
            var output = document.getElementById('profilePicPreview');
            output.src = $("#ProfilePictureUrl").val();
        })
        $("#ProfilePictureUrl").on("change", function () {
            var output = document.getElementById('profilePicPreview');
            output.src = $(this).val();
        })
    </script>
}

E-Tickets/Views/Actors/Edit.cshtml
@model Actor


<div class="container mt-5">
    <div class="row m-auto">



        <div class="col-md-8 col-sm-8 col-10">
            <form asp-action="Edit">
                <div class="form-group">
                    <div asp-validation-summary="ModelOnly"></div>

                </div>
                <div class="form-group text-center">
                    <img id="profilePicPreview" width="200" />
                </div>
                <input asp-for="Id" id="Id" type="text" class="form-control" hidden>

                <div class="form-group">
                    <label asp-for="ProfilePictureUrl">Profile Picture Url</label>
                    <input asp-for="ProfilePictureUrl" id="ProfilePictureUrl" type="text" class="form-control">
                    <span asp-validation-for="ProfilePictureUrl"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FullName">Full Name</label>
                    <input asp-for="FullName" type="text" class="form-control">
                    <span asp-validation-for="FullName"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Bio">Bio</label>
                    <input asp-for="Bio" type="text" class="form-control">
                    <span asp-validation-for="Bio"></span>
                </div>

                <button type="submit" value="Edit" class="btn btn-info">Submit</button>
                <a asp-action="Index" class="btn btn-outline-success">Show All</a>
            </form>
        </div>

    </div>
</div>


@section Scripts{

    <script>
        $(document).ready(function () {
            var output = document.getElementById('profilePicPreview');
            output.src = $("#ProfilePictureUrl").val();
        })
        $("#ProfilePictureUrl").on("change", function () {
            var output = document.getElementById('profilePicPreview');
            output.src = $(this).val();
        })
    </script>
}

E-Tickets/Views/Actors/Index.cshtml
@model IEnumerable<Actor>


<div class="container my-5">

    <a class="btn btn-success" asp-action="Create">Add Actor</a>
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>@Html.DisplayNameFor(model => model.Id)</th>
                <th>@Html.DisplayNameFor(model => model.ProfilePictureUrl)</th>
                <th>@Html.DisplayNameFor(model => model.FullName)</th>
                <th>@Html.DisplayNameFor(model => model.Bio)</th>
                <th>Actions</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@Html.DisplayFor(modelItem => item.Id)</th>
                    <td><img src="@Html.DisplayFor(model => item.ProfilePictureUrl)" style="width:100px" alt="Image" /></td>
                    <td>@Html.DisplayFor(modelItem => item.FullName)</td>
                    <td>@Html.DisplayFor(modelItem => item.Bio)</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary"> <img src="~/Images/view.png" /> Details</a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>



                    </td>
                </tr>
            }

            </tbody>
    </table>




</div> 

E-Tickets/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

E-Tickets/Views/Movies/Index.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "List of Movies";
}


<div class="container mb-5">
    <div class="row ">
        @foreach (var item in Model)
        {
            <div class="col-md-6">
                <div class="card">
                    <div class="d-flex justify-content-between p-3 text-white" style="background: #05A499 ">

                        <h6>
                            @item.Name
                        </h6>

                        <img src="~/Images/edit.png" width="30" height="30" />



                    </div>
                    <div class="d-flex">
                        <div>
                            <img src="@item.ImageUrl" style="width:200px;height:100%" />
                        </div>
                        <div class="text-center p-2">
                            <p><b>this is the @item.Name</b></p>
                            <p> <b>Description @item.Description</b></p>
                            <p><b>Cinema : @item.Cinema.Name </b>  </p>
                            <p><b>Category : @item.MovieCategorey</b>  </p>
                            <p><b>Start Date : @item.StartDate.ToString("dd MMM yy") </b>  </p>
                            <p><b>End Date : @item.EndDate.ToString("dd MMM yy") </b>  </p>
                            <b>Status : </b>
                            @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                            {
                                <span class="bg-info text-white p-1" style="border-radius:20px;font-size:.8rem"> AVAILABLE </span>
                            }
                            else if (DateTime.Now > item.EndDate)
                            {
                                <span class="bg-info text-white p-1" style="border-radius: 20px; font-size: .8rem"> EXPIRED </span>

                            }
                            else
                            {
                                <span class="bg-info text-white p-1" style="border-radius: 20px; font-size: .8rem">UPCOMING  </span>

                            }



                        </div>

                    </div>
                    <div class="d-flex  p-2 text-white" style="background: #05A499 ">
                        <a href="#" class="mx-2 btn btn-success"><img src="~/Images/shopping-cart.png" alt="Cart" /> Add To Cart ( Price : @item.Price $) </a>
                        <a href="#" class="mx-2 btn btn-info"><img src="~/Images/view.png" /> Details</a>



                    </div>
                </div>
            </div>

        }
    </div>

</div>

E-Tickets/Views/NotFound.cshtml
<h1>Page Not Found</h1>

E-Tickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Tickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E_Tickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Index">Actors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - E_Tickets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>